### PR TITLE
Small enhancements

### PR DESCRIPTION
**Pull request by thomasletsch**
Hi Israel,

I made two small enhancements:
- Cleaning up dependencies. Made the standard libs as "provided" to avoid versioning conflicts on user side. Also removed the SLF4J Log4J dependency since a library that only depends on the SLF4J-API gives the use the possibility to chose the SLF4J implementation.
- Small logging changes. Added logging HTTP method (testing rest interface for which this was quite helpful). Skip logging of binary content (I return also images and that should not be logged).

What do you think about these changes?

R.,
Thomas

### CODE REVIEW

**Comment by krasinski** [comment]
@isrsal any chance for merging this pull request?

**Comment by isrsal** [comment]
@krasinski sorry I wasn't paying attention. I'll review and merge.

**Comment by isrsal** [comment]
@krasinski I merged. I'd have to rebuild and upload to sonatype, so it's available in maven central

**Comment by krasinski** [comment]
@isrsal thank you for a very fast reaction, I'm waiting for the release

**Comment by thomasletsch** [comment]
@isrsal Thanks for merging it!

**Comment by krasinski** [comment]
@isrsal When can we expect a release?

**Pull request merged**
